version: '3.8'

services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      - JAVA_MEMORY=2G  # Adjust based on your system's available memory
      - DEBUG=false
    volumes:
      - minecraft-data:/data
    tty: true
    stdin_open: true

volumes:
  minecraft-data:
    driver: local
